site_name: 我的技术写作
site_author: leo
site_url: https://leosirius.github.io/tech_writing/
docs_dir: ./docs

repo_name: tech_writing
repo_url: https://github.com/LeoSirius/tech_writing/

theme:
  name: material
  palette:
    primary: light green
    accent: light green
  favicon: logo.png
  logo: logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky


markdown_extensions:
  - pymdownx.highlight:
    linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite